import { describe, it, expect } from 'vitest';
import { catalog, eq, all, either } from '../src/engine/catalog';
import { evaluate, evaluateCase, resolveQuestionnaire, validateValue, infer } from '../src/engine/evaluate';
import { matches, canonical } from '../src/engine/logic';
import { validateCatalog, seedScenarioAudit } from '../src/engine/validate';
import { assessment, declared, hr, provider, gpai } from './helpers';
import type { Value } from '../src/domain/model';
const one=(v:Record<string,Value>={},date?:string)=>evaluateCase(assessment(v,date),'case-one');
const has=(v:Record<string,Value>,id:string)=>one(v).findings.some(x=>x.id===id);

describe('Contratos e incertidumbre',()=>{
  it('valida el catálogo completo y los hashes originales',()=>expect(validateCatalog()).toMatchObject({valid:true,errors:[]}));
  it('distingue UNKNOWN de NO',()=>{expect(matches(eq('A6-001','NO'),{'response.a6_001':'UNKNOWN'})).toBe('UNKNOWN');expect(matches({not:eq('A6-001','YES')},{'response.a6_001':'UNKNOWN'})).toBe('UNKNOWN');});
  it('aplica lógica ternaria AND y OR',()=>{expect(matches(all(eq('A6-001','YES'),eq('A6-002','YES')),{'response.a6_001':'NO'})).toBe(false);expect(matches(either(eq('A6-001','YES'),eq('A6-002','YES')),{'response.a6_001':'YES'})).toBe(true);});
  it('permite una regla explícita de revisión por UNKNOWN',()=>expect(matches(eq('A6-001','UNKNOWN'),{'response.a6_001':'UNKNOWN'})).toBe(true));
  it('rechaza inyectar roles en respuestas',()=>expect(()=>validateValue('role','PROVIDER')).toThrow('desconocida'));
  it('rechaza mezclar opciones exclusivas y múltiples',()=>expect(()=>validateValue('TR-003',['TEXT','UNKNOWN'])).toThrow('exclusiva'));
  it('rechaza la cardinalidad incorrecta',()=>expect(()=>validateValue('USE-001','HR')).toThrow('múltiple'));
  it('es determinista aunque cambie el orden de entrada',()=>{const a=assessment(hr);const b=structuredClone(a);b.cases[0].answers=Object.fromEntries(Object.entries(b.cases[0].answers).reverse());expect(canonical(evaluate(a))).toBe(canonical(evaluate(b)));});
  it('distingue los fixtures de módulo heredados',()=>expect(seedScenarioAudit().results.filter(x=>x.kind==='MODULE_FIXTURE')).toHaveLength(5));
  it('la huella canónica coincide después de serializar propiedades opcionales',()=>{const v={a:undefined,b:[1,undefined],c:{x:'yes',y:undefined}};expect(canonical(v)).toBe(canonical(JSON.parse(JSON.stringify(v))));});
});

describe('Escenarios jurídicos de respuestas (expectativas de borrador)',()=>{
  it('01: asistente de emails no activa alto riesgo',()=>expect(one().classifications).toEqual(['MINIMAL_OR_OTHER_RISK']));
  it('02: alfabetización organizativa no se repite por caso',()=>{const a=assessment();a.cases.push({...a.cases[0],id:'second'});const r=evaluate(a);expect(r.organisationFindings).toHaveLength(1);expect(r.cases.flatMap(x=>x.findings).some(x=>x.id==='OBL-AI-LITERACY-001')).toBe(false);});
  it('03: proveedor de chatbot con interacción no evidente',()=>expect(has({...provider,'FUNC-001':['DIRECT_INTERACTION'],'TR-001':'YES','TR-002':'NO'},'OBL-TR-DIRECT-INTERACTION-001')).toBe(true));
  it('04: no atribuye automáticamente art.50.1 al simple usuario de chatbot',()=>expect(has({'FUNC-001':['DIRECT_INTERACTION'],'TR-001':'YES','TR-002':'NO'},'OBL-TR-DIRECT-INTERACTION-001')).toBe(false));
  it('05: filtrar candidatos y elaborar perfiles activa alto riesgo',()=>expect(one(hr).classifications).toContain('HIGH_RISK'));
  it('06: redactar ofertas no activa por sí solo alto riesgo',()=>expect(one({'USE-001':['HR'],'HR-001':['WRITE_JOB_ADS']}).classifications).not.toContain('HIGH_RISK'));
  it('07: profiling desconocido mantiene candidato',()=>expect(one({...hr,'A6-001':'UNKNOWN'}).classifications).toContain('HIGH_RISK_CANDIDATE'));
  it('08: excepción requiere riesgo significativo descartado y documento',()=>expect(one({...hr,'A6-001':'NO','A6-002':'YES','A6-006':'NO'}).classifications).not.toContain('NOT_HIGH_RISK_ARTICLE_6'));
  it('09: excepción declarada y documentada mantiene advertencia',()=>{const r=one({...hr,'A6-001':'NO','A6-002':'YES','A6-006':'NO','A6-007':'NO','A6-008':'YES'});expect(r.classifications).toContain('NOT_HIGH_RISK_ARTICLE_6');expect(r.warnings).toContain('ARTICLE_6_ASSESSMENT_NOT_VERIFIED');});
  it('10: influencia considerable descarta excepción',()=>expect(one({...hr,'A6-001':'NO','A6-006':'YES'}).classifications).toContain('HIGH_RISK'));
  it('11: ausencia de condiciones de excepción conserva art.6.2',()=>expect(one({...hr,'A6-001':'NO','A6-002':'NO','A6-003':'NO','A6-004':'NO','A6-005':'NO'}).classifications).toContain('HIGH_RISK'));
  it('12: alto riesgo y transparencia coexisten',()=>{const r=one({...hr,...provider,'SYS-006':'YES','FUNC-001':['CLASSIFY','DIRECT_INTERACTION'],'TR-001':'YES','TR-002':'NO'});expect(r.roles).toEqual(['DEPLOYER','PROVIDER']);expect(r.classifications).toContain('HIGH_RISK');expect(r.classifications).toContain('TRANSPARENCY_OBLIGATIONS');});
  it('13: emociones en trabajo sin excepción requiere revisión de prohibición',()=>expect(one({'USE-001':['EMOTION'],'FUNC-001':['EMOTION_RECOGNITION'],'PERSON-001':['EMPLOYEES'],'PROH-005':'YES','PROH-006':'NO'}).classifications).toContain('POTENTIALLY_PROHIBITED'));
  it('14: excepción médica impide ese disparador automático',()=>expect(one({'FUNC-001':['EMOTION_RECOGNITION'],'PROH-005':'YES','PROH-006':'YES'}).classifications).not.toContain('POTENTIALLY_PROHIBITED'));
  it('15: consentimiento desconocido no equivale a falta de consentimiento',()=>expect(one({'FUNC-001':['GENERATE_VIDEO'],'TR-003':['VIDEO'],'PROH-008':'YES','PROH-014':'UNKNOWN'}).classifications).not.toContain('POTENTIALLY_PROHIBITED'));
  it('16: material íntimo sin consentimiento produce alerta',()=>expect(one({'FUNC-001':['GENERATE_VIDEO'],'TR-003':['VIDEO'],'PROH-008':'YES','PROH-014':'NO'}).classifications).toContain('POTENTIALLY_PROHIBITED'));
  it('17: contenido sintético no equivale automáticamente a deepfake',()=>expect(has({'FUNC-001':['GENERATE_IMAGE'],'TR-003':['IMAGE'],'TR-004':'NO'},'OBL-TR-DEEPFAKE-001')).toBe(false));
  it('18: publicar deepfake siendo deployer',()=>expect(has({'FUNC-001':['GENERATE_VIDEO'],'TR-003':['VIDEO'],'TR-004':'YES'},'OBL-TR-DEEPFAKE-001')).toBe(true));
  it('19: revisión editorial conserva excepción de texto público',()=>expect(has({'TR-005':'YES','TR-006':'YES'},'OBL-TR-PUBLIC-TEXT-001')).toBe(false));
  it('20: texto de interés público sin revisión dispara transparencia',()=>expect(has({'TR-005':'YES','TR-006':'NO'},'OBL-TR-PUBLIC-TEXT-001')).toBe(true));
  it('21: ya informar de biometría no elimina la existencia de la obligación',()=>expect(has({'FUNC-001':['BIOMETRIC_CATEGORISE'],'TR-007':'YES'},'OBL-TR-EMOTION-BIOMETRIC-001')).toBe(true));
  it('22: logs solo cuando están bajo control',()=>{expect(has({...hr,'DEP-015':'NO'},'OBL-DEP-LOGS-001')).toBe(false);expect(has({...hr,'DEP-015':'YES'},'OBL-DEP-LOGS-001')).toBe(true);});
  it('23: datos de entrada se condicionan al control',()=>expect(has({...hr,'DEP-014':'NO'},'OBL-DEP-INPUT-DATA-001')).toBe(false));
  it('24: una falta de evidencia no implica incumplimiento',()=>expect(one(hr).findings.every(f=>f.status==='UNKNOWN')).toBe(true));
  it('25: GPAI abierto sin riesgo sistémico conserva documentación exceptuada',()=>{expect(has({...gpai,'GPAI-002':'YES'},'OBL-GPAI-TECH-DOC-001')).toBe(false);expect(has({...gpai,'GPAI-002':'YES'},'OBL-GPAI-COPYRIGHT-001')).toBe(true);});
  it('26: GPAI abierto con riesgo sistémico recupera documentación',()=>expect(has({...gpai,'GPAI-002':'YES','GPAI-003':'YES'},'OBL-GPAI-TECH-DOC-001')).toBe(true));
  it('27: excepción GPAI desconocida no se transforma en NO',()=>expect(has({...gpai,'GPAI-002':'UNKNOWN'},'OBL-GPAI-TECH-DOC-001')).toBe(false));
  it('28: Anexo I no se certifica con dos respuestas genéricas',()=>{const r=one({'USE-001':['AI_IN_PRODUCTS'],'ANNEX1-001':'YES','ANNEX1-002':'YES'});expect(r.classifications).toContain('HIGH_RISK_CANDIDATE');expect(r.classifications).not.toContain('HIGH_RISK');});
  it('29: un usuario no puede autoexcluirse por open source',()=>expect(one({'SCOPE-005':'YES','SCOPE-006':'NONE'}).classifications).not.toContain('OUT_OF_SCOPE'));
  it('30: uso personal marca revisión sin excluir al proveedor',()=>expect(one({...provider,'SCOPE-001':'YES'}).scope).toBe('REVIEW_REQUIRED'));
  it('31: futuro y frontera de aplicación Anexo III',()=>{expect(one(hr,'2027-12-01').findings.find(f=>f.id==='OBL-DEP-INSTRUCTIONS-001')?.temporal).toBe('FUTURE');expect(one(hr,'2027-12-02').findings.find(f=>f.id==='OBL-DEP-INSTRUCTIONS-001')?.temporal).toBe('CURRENT');});
  it('32: los transitorios no se dan por resueltos',()=>expect(one({...hr,'TIME-001':'YES'},'2028-01-01').findings.find(f=>f.id==='OBL-DEP-INSTRUCTIONS-001')?.temporal).toBe('TRANSITION_REVIEW'));
  it('33: fecha anterior al snapshot no inventa historia',()=>expect(one(hr,'2026-01-01').warnings).toContain('HISTORICAL_SNAPSHOT_UNSUPPORTED'));
  it('34: fraude comercial no abre rama policial',()=>{const a=assessment({'USE-001':['SECURITY'],'LAW-002':'NO','LAW-001':'CRIMINAL_PROFILING'});expect(resolveQuestionnaire({...a.organisationAnswers,...a.cases[0].answers}).inactive).toContain('LAW-001');});
  it('35: datos personales detectan ámbito externo sin evaluar RGPD',()=>expect(one({'DATA-001':'YES'}).relatedDomains.join(' ')).toContain('no evaluada'));
  it('36: hechos y trazas llevan origen y dependencias',()=>{const r=one(hr);const f=r.findings.find(f=>f.id==='OBL-DEP-INSTRUCTIONS-001')!;expect(f.answerIds).toContain('HR-001');expect(r.facts.every(f=>f.provenance==='DECLARED')).toBe(true);expect(f.rules.length).toBeGreaterThan(0);});
  it('37: el punto 2 del anexo III queda fuera de la FRIA pública',()=>{const values={'USE-001':['CRITICAL_INFRA'],'INFRA-001':'ELECTRICITY','A6-001':'YES','FRIA-001':'YES'} as Record<string,Value>;const a=assessment(values);const q=resolveQuestionnaire({...a.organisationAnswers,...a.cases[0].answers});expect(q.inactive).toContain('FRIA-001');expect(q.active.map(x=>x.id)).not.toContain('FRIA-002');expect(has(values,'OBL-FRIA-001')).toBe(false);});
  it('38: la FRIA pública sigue aplicándose a otros casos del anexo III',()=>expect(has({...hr,'FRIA-001':'YES'},'OBL-FRIA-001')).toBe(true));
  it('39: marca o modificación abre el detalle del artículo 25',()=>{const a=assessment({...hr,'SYS-003':'YES','ROLE-004':'YES'});const q=resolveQuestionnaire({...a.organisationAnswers,...a.cases[0].answers});expect(q.active.map(x=>x.id)).toEqual(expect.arrayContaining(['ROLE-004','ROLE-005','ROLE-006']));expect(evaluateCase(a,'case-one').roles).toContain('PROVIDER');});
});
