import { describe,it,expect,beforeEach,afterEach } from 'vitest';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Store,Conflict } from '../src/storage/store';
import { mutate } from '../src/application/service';
import { evaluate, nextQuestions } from '../src/engine/evaluate';
import { exportReport,html,compareResults } from '../src/reports/generate';
import { inspectRepo } from '../src/application/inspect';
import { assessment,stamp } from './helpers';
let root:string;let store:Store;
beforeEach(async()=>{root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'ai-act-test-')));store=new Store(root);});
afterEach(async()=>{await fs.rm(root,{recursive:true,force:true});});
async function draft(){let a=await store.create({name:'Prueba ficticia',mode:'MIXED',evaluationDate:'2026-09-13'});return mutate(store,a.id,a.version,{action:'case.add',name:'Chatbot'});}
describe('Persistencia y API de aplicación',()=>{
  it('guarda y recupera un expediente entre instancias',async()=>{const a=await draft();expect(await new Store(root).read(a.id)).toEqual(a);});
  it('detecta conflictos concurrentes',async()=>{const a=await draft();await mutate(store,a.id,a.version,{action:'case.add',name:'Segundo'});await expect(mutate(store,a.id,a.version,{action:'case.add',name:'Tercero'})).rejects.toBeInstanceOf(Conflict);});
  it('rechaza traversal en identificadores',async()=>await expect(store.read('../secrets')).rejects.toThrow());
  it('rechaza symlinks de expediente',async()=>{await fs.symlink(os.tmpdir(),path.join(root,'linked'),'junction');await expect(store.read('linked')).rejects.toThrow('enlazado');});
  it('valida fecha y estados derivados',async()=>{await expect(store.create({name:'Bad',evaluationDate:'2026-02-30'})).rejects.toThrow();const a=await draft();await expect(mutate(store,a.id,a.version,{action:'answer',caseId:a.cases[0].id,questionId:'role',value:'PROVIDER'})).rejects.toThrow();});
  it('rechaza contestar una rama no activa',async()=>{const a=await draft();await expect(mutate(store,a.id,a.version,{action:'answer',caseId:a.cases[0].id,questionId:'HR-001',value:['FILTER_CV']})).rejects.toThrow('no está activa');});
  it('el cambio de uso invalida ramas y preserva historial',async()=>{let a=await draft();const cid=a.cases[0].id;for(const [questionId,value]of [['USE-001',['HR']],['HR-001',['FILTER_CV']],['A6-001','YES']] as const)a=await mutate(store,a.id,a.version,{action:'answer',caseId:cid,questionId,value});expect(evaluate(a).cases[0].classifications).toContain('HIGH_RISK');a=await mutate(store,a.id,a.version,{action:'answer',caseId:cid,questionId:'USE-001',value:['MARKETING']});expect(a.cases[0].answers['HR-001']).toBeUndefined();expect(evaluate(a).cases[0].classifications).not.toContain('HIGH_RISK');expect(a.events.some(e=>e.type==='ANSWER_INVALIDATED')).toBe(true);});
  it('propuestas de IA no cambian el diagnóstico hasta confirmar',async()=>{let a=await draft();const cid=a.cases[0].id;a=await mutate(store,a.id,a.version,{action:'evidence.import',observations:[{id:'obs-one',caseId:cid,title:'Hipótesis',description:'Puede usar una herramienta externa',provenance:'INFERRED',source:'CODE',locator:'src/example.ts:1',collectedAt:stamp,method:'lectura'}],proposals:[{id:'proposal-one',caseId:cid,questionId:'SYS-001',value:'THIRD_PARTY_TOOL',evidenceIds:['obs-one'],reason:'Requiere confirmar'}]});expect(evaluate(a).cases[0].roles).toEqual([]);a=await mutate(store,a.id,a.version,{action:'proposal.resolve',proposalId:'proposal-one',accept:true});expect(evaluate(a).cases[0].roles).toContain('DEPLOYER');expect(a.cases[0].answers['SYS-001'].provenance).toBe('DECLARED');});
  it('sellado es inmutable, reproducible y permite una nueva revisión',async()=>{const a=await draft();const {snapshotId,assessment:sealed}=await store.seal(a.id,a.version);const s=await store.snapshot(a.id,snapshotId);expect(s.evaluation).toEqual(evaluate(a));await expect(mutate(store,a.id,sealed.version,{action:'case.add',name:'No'})).rejects.toThrow('sellada');const revised=await store.fork(a.id);expect(revised.id).not.toBe(a.id);expect(revised.status).toBe('DRAFT');expect((await store.read(a.id)).status).toBe('SEALED');});
  it('detecta alteración de snapshot',async()=>{const a=await draft();const {snapshotId}=await store.seal(a.id,a.version);const p=path.join(root,a.id,'revisions',`${snapshotId}.json`);const s=JSON.parse(await fs.readFile(p,'utf8'));s.evaluation.evaluationDate='2030-01-01';await fs.writeFile(p,JSON.stringify(s));await expect(store.snapshot(a.id,snapshotId)).rejects.toThrow('integridad');});
  it('no sigue un directorio de informes enlazado',async()=>{const a=await draft();await fs.symlink(os.tmpdir(),path.join(root,a.id,'reports'),'junction');await expect(store.writeReport(a.id,'report.md','x')).rejects.toThrow('enlazada');});
});
describe('Recorrido completo y exportaciones',()=>{
  it('responde desde la primera pregunta hasta el resultado sin estados inyectados',async()=>{let a=await draft();const cid=a.cases[0].id;const data=assessment();const desired={...data.organisationAnswers,...data.cases[0].answers};let answered=0;for(let n=0;n<200;n++){const q=nextQuestions(a,cid).pending[0];if(!q)break;const val=desired[q.id]?.value??(q.answer_type==='MULTI'?['UNKNOWN']:'UNKNOWN');a=await mutate(store,a.id,a.version,{action:'answer',caseId:cid,questionId:q.id,value:val});answered++;}expect(answered).toBeGreaterThan(20);expect(nextQuestions(a,cid).pending).toHaveLength(0);expect(evaluate(a).cases[0].roles).toContain('DEPLOYER');});
  it.each(['md','html','pdf','docx','json'])('genera un informe %s válido',async(format)=>{const a=assessment();const r=evaluate(a);const buffer=await exportReport(a,r,format);expect(buffer.length).toBeGreaterThan(500);if(format==='pdf')expect(buffer.subarray(0,5).toString()).toBe('%PDF-');if(format==='docx')expect(buffer.subarray(0,2).toString()).toBe('PK');if(format==='json')expect(JSON.parse(buffer.toString())).toEqual(r);if(format==='html')expect(buffer.toString()).toContain('lang="es"');});
  it('escapa HTML de contenido no confiable',()=>{const a=assessment();a.name='<img src=x onerror=alert(1)>';expect(html(a,evaluate(a))).not.toContain('<img');expect(html(a,evaluate(a))).toContain('&lt;img');});
  it('la comparación detecta eliminación de casos',()=>{const a=assessment();const b=structuredClone(a);b.cases=[];expect(compareResults(evaluate(a),evaluate(b)).changes[0].type).toBe('REMOVED_CASE');});
  it('inspección estática omite secretos, symlinks y no ejecuta el objetivo',async()=>{await fs.writeFile(path.join(root,'example.ts'),'import OpenAI from "openai";\n// candidato');await fs.writeFile(path.join(root,'.env'),'SECRET=very-private\nopenai');await fs.symlink(path.join(root,'.env'),path.join(root,'linked.ts'));const r=await inspectRepo(root);expect(r.summary.scanned).toBe(1);expect(r.observations.length).toBeGreaterThan(0);expect(JSON.stringify(r)).not.toContain('very-private');expect(r.proposals).toEqual([]);});
});
